<?php 
return ['apartments' => [
    [
        "user_id" => 1,
        "title" => "Casa Aurora",
        "rooms" => 8,
        "beds" => 10,
        "bathrooms" => 3,
        "square_meters" => 400,
        "address" => "Via Riccardo Pitteri, 4, 20134 Milano MI",
        "cover_img" => "",
        "visible" => 1, 
        "lat" => 45.47294,
        "lon" => 9.24909,
    ],
    [
        "user_id" => 1,
        "title" => "Villa Serena",
        "rooms" => 5,
        "beds" => 7,
        "bathrooms" => 2,
        "square_meters" => 320,
        "address" => "Via Stefano Canzio, 2, 20131 Milano MI",
        "cover_img" => "",
        "visible" => 0, 
        "lat" => 45.485183,
        "lon" => 9.217643,
    ],
    [
        "user_id" => 1,
        "title" => "Rifugio Verde",
        "rooms" => 12,
        "beds" => 18,
        "bathrooms" => 5,
        "square_meters" => 1000,
        "address" => "Via della Moscova, 23, 20121 Milano MI",
        "cover_img" => "",
        "visible" => 1, 
        "lat" => 45.476711,
        "lon" => 9.190068,
    ],
    [
        "user_id" => 1,
        "title" => "Dimora Primavera",
        "rooms" => 3,
        "beds" => 3,
        "bathrooms" => 2,
        "square_meters" => 222,
        "address" => "Via Pietro Marussig, 2, 20154 Milano MI",
        "cover_img" => "",
        "visible" => 1, 
        "lat" => 45.486764,
        "lon" => 9.165696,
    ],
    [
        "user_id" => 1,
        "title" => "Tenuta Tranquilla",
        "rooms" => 6,
        "beds" => 9,
        "bathrooms" => 4,
        "square_meters" => 401,
        "address" => "Via Antonio Canova, 23, 20145 Milano MI",
        "cover_img" => "",
        "visible" => 0, 
        "lat" => 45.475586,
        "lon" => 9.168440,
    ],
    [
        "user_id" => 1,
        "title" => "Chalet Alpino",
        "rooms" => 2,
        "beds" => 3,
        "bathrooms" => 1,
        "square_meters" => 101,
        "address" => "Via Fratelli Ruffini, 10, 20123 Milano MI",
        "cover_img" => "",
        "visible" => 1, 
        "lat" => 45.466811,
        "lon" => 9.169555,
    ],
    [
        "user_id" => 1,
        "title" => "Residenza Luminosa",
        "rooms" => 20,
        "beds" => 30,
        "bathrooms" => 6,
        "square_meters" => 1500,
        "address" => "Via San Vittore, 24, 20123 Milano MI",
        "cover_img" => "",
        "visible" => 0, 
        "lat" => 45.463636,
        "lon" => 9.169360,
    ],
    [
        "user_id" => 1,
        "title" => "Cottage Fiorito",
        "rooms" => 6,
        "beds" => 12,
        "bathrooms" => 2,
        "square_meters" => 800,
        "address" => "Ripa di Porta Ticinese, 3, 20143 Milano MI",
        "cover_img" => "",
        "visible" => 1, 
        "lat" => 45.452298,
        "lon" => 9.177274,
    ],
]];